= Accessing content from Publishers - Mechanisms and limitations

Creating an interoperable layer for machine access to OA content from publishers for TDM

== Overview
Todo

== Elsevier
=== Publisher APIs
//From: https://docs.google.com/document/d/1xFpoXGd0kQ-9FcjqgMe38pdsChvl2-JGAVXv09f3cZA
//What does the publisher API actually offers
Elsevier provides us with all their items with no restriction by API key.

==== Initial data import
Provides a sitemap listing all items by Journal (alphabetically) +
http://api.elsevier.com/sitemap/page/sitemap/index.html

The sitemap structure is:

* Titles starting with [a-z,0-9] > +
    ** ‘List of Journal Titles’ > ‘List of *Volumes*’ > ‘List of Items in Volume’ > Metadata for Item +
    ** ‘List of *Book Titles*’ > ‘Book ID’ > ‘List of Items in Book’ > Metadata for Item (usually per chapter) +

For accessing the sitemap, Metadata or Open Access Full-text items, there is no limit of the number of requests we can issue. We have found that we can make at least 10,000 requests/hour for downloading PDF’s.

An open access item can be determined by checking:
[source,xml]
<full-text-retrieval-response>
  <coredata>
    <openaccess>1</openaccess>
    <openaccessArticle>true</openaccessArticle>
    <openaccessType>Full</openaccessType>
  </coredata>
</full-text-retrieval-response>

If those fields are all 1 or true, the item is truly open access and you can download the PDF by visiting the link with ?httpAccept=application/pdf appended.

==== Keeping updated
We recrawl the sitemaps up to the harvested journal *Volume* OR *Book Title*. If we have already crawled the file, we do not recrawl. We will always skip ‘Article in Press’ links until they are formed into a complete Volume/Issue.

The Full-text can be retrieved by submitting the ‘Metadata for Item’ link with the http accept header as application/pdf.

The metadata link example: +
https://api.elsevier.com/content/article/pii/S0001-4575(15)30158-5

Append ?httpAccept=application/xml for metadata +
https://api.elsevier.com/content/article/pii/S0001-4575(15)30158-5?httpAccept=application/xml

Append ?httpAccept=application/pdf for pdf +
https://api.elsevier.com/content/article/pii/S0001-4575(15)30158-5?httpAccept=application/pdf

The article metadata view states whether the item is Open Access as well as a detailed metadata view.

=== Harvesting approach
Description of the approach we take to harvest the publisher

=== Limitations
//Limitations on doing what we need to do (recognizing something is OA, rate limits, discovery of new DOIS, access to PDFs, etc. ) - this will be presented as features in a table

//From: https://docs.google.com/document/d/1tlrSEjDjKrUAZ00JR8FvJJFJMuT1UKM7iX7uUU4lFho
[cols="3*"]
|====
|Task|Limitation|Solution

|Retrieving list of all items
|To get a list of all items available in Elsevier, you must crawl sitemaps in order to get the list
|Build a custom crawler to get all items in Elsevier.

|Updating a list of DOI’s
|Once the sitemaps have been harvested, it is not easy to get a list of additions since the last harvest without re-crawling
|

|
|Elsevier API is has probably a throttling limit for the number of requests. We believe the limit is somewhere around 3 per second
|
|====

=== Proposed improvements
Recommendations for the publisher on improvements (e.g. increase the rate limits,
  provide a solution for discoverability of DOIs, provide these necessary metadata fields,
  license metadata are missing in CrossRef)

=== OMTD Schema Mapping
Mapping of fields to the OMTD schema (i.e. towards achieving content interoperability) -
maybe we can make our life easier by saying that we rely on the CrossRef TDM service to
harmonize the metadata and we can then only comment on the conversion of CrossRef TDM schema to the OMTD schema

== Springer

=== Publisher APIs
The API provided by springer only allows 5,000 requests / API key / day. The search only allows a maximum of 20 items per request. Also, it is impossible to retrieve the 10,000th page if we were to iterate over a query of * of 20 items / page. Springer reports over 295,000 Open Access items.

http://api.springer.com/openaccess/app?api_key=fdcc8721a1359724c6260b04d2ced9b2&q=*&s=10000&p=20&


For the Springer API, it would be best to get content via the CrossRef API

=== Harvesting approach

=== Limitations

=== Proposed improvements

=== OMTD Schema Mapping