== CrossRef

=== Publisher APIs

CrossRef is not a traditional publisher but the prominent DOI Registration Agency.
iscovery of DOIs
We use CrossRef Metadata API (CrossRef is the prominent DOI Registration Agency*) to discover doi s of published articles of the big publishers
The way to do this:


Discover member, e.g. discover springer:
http://api.crossref.org/members?query=springer


Retireve prefixes from results
message->items[]->prefixes[]
E.g. retrieve works by springer (springer different than Springer Nature)
http://api.crossref.org/works?filter=prefix:10.1891
You can paginate over results by rows and offset parameters e.g
http://api.crossref.org/works?filter=prefix:10.1891,rows:10,offset:1000
However if you try to navigate to more than 10k then you encounter the deep paging problem. In such case you can use a cursor to navigate into large result sets, e.g.:
1st request:
http://api.crossref.org/works?filter=prefix:10.1891&cursor=*
The response gives a next-cursor which if followed can retrieve the next page (then retireve the next cursor to retrieve next page etc.). This is essentially the equivalent of resumptionToken of OAI-PMH protocol
http://api.crossref.org/works?filter=prefix:10.1891&cursor=AoE/CWh0dHA6Ly9keC5kb2kub3JnLzEwLjE4OTEvMDE5OC04Nzk0LjI4LjM=



=== Harvesting approach

=== Limitations

[cols="2*"]
|====
|Task|Limitation

|Doi discovery
|CrossRef as the de-facto doi registration agency naturaly imposes no restriction in discovering DOIs, offering quite handful methods to do so (e.g. by member, by native query, by funder) and utilising cursors to address deep-paging issues.

|Incremental updates
|Result set from a certain date (or even between a time window) can be obtained via the from-XXX-date,until-XXX-date (XXX marks different dates in publication record lifecycle and can be deposit-date, index-date, update-date, created date, pub-date)

|Imposed limits
|Though not explicitly enforced, CrossRef preserves the right to throttle requests to a limit that ensures that the service remains usable.From the website:

----

From time to time Crossref needs to impose rate limits to ensure that the free API is usable by all. Any rate limits that are in effect will be advertised in the X-Rate-Limit-Limit and X-Rate-Limit-Interval HTTP headers.

----

|Response formats
|Results are returned in JSON format. Though Json natively avoids enforcing explicit schema (i.e. is schema free), results in CrossRef data model (documentation of this domain can be found https://github.com/CrossRef/rest-api-doc/blob/master/api_format.md[here] )
|====

=== Proposed improvements


