= Accessing content from Publishers - Mechanisms and limitations

== Overview

Purpose of this document is to present harvesting capabilities of major scientific literature publishers and data providers via machine protocols and highlight limitations of accessing content in large scale through these interfaces. A possible harvesting approach is presented for each publisher and how each publisher's data can be mapped to https://github.com/openminted/omtd-share_metadata_schema[OpenMinTeD publication schema]. Ultimate goal is to create an  interoperable layer for machine access to OA content from publishers for TDM purposes.

This is an dynamic page, should be updated every time a machine interface of a publisher is altered.

== Why is this needed?

- Creating a seamless layer for accessing content across publishers.
- Many TDM applications require local access to a large (or even full) corpus of scientific publications. These applications often cannot rely on TDM APIs already provided by some publishers.
- Harvesting large datasets of scientific content takes considerable time and computational resources. Creating an up-to-date cache of scientific documents readily available for processing lowers the barriers for TDM of scientific literature.


== Key publishers

We investigate, analyse and document the functionality exposed by APIs of publishers with respect to being able to aggregate open access content from them. We aim at implementing custom solutions for aggregating content from the following key publishers:

=== https://github.com/openminted/omtd-publisher-connector-harvester/blob/master/interoperability-layer/elsevier.adoc[Elsevier]

=== https://github.com/openminted/omtd-publisher-connector-harvester/blob/master/interoperability-layer/springer.adoc[Springer]

=== https://github.com/openminted/omtd-publisher-connector-harvester/blob/master/interoperability-layer/Wiley.adoc[Wiley]

=== https://github.com/openminted/omtd-publisher-connector-harvester/blob/master/interoperability-layer/taylorNFrancis.adoc[TaylorFrancis]

=== https://github.com/openminted/omtd-publisher-connector-harvester/blob/master/interoperability-layer/PLoS.adoc[PLoS]

== Other publishers

The content from many publishers not covered in the section above can still be collected using an approach in which we make use of the CrossRef service.

=== https://github.com/openminted/omtd-publisher-connector-harvester/blob/master/interoperability-layer/crossref.adoc[CrossRef]

