= Accessing content from Publishers - Mechanisms and limitations

== Overview

Purpose of this document is to present harvesting capabilities of major scientific literature publishers and data providers via machine protocols and highlight limitations of accessing content in large scale through these interfaces. A possible harvesting approach is presented for each publisher and how each publisher's data can be mapped to https://github.com/openminted/omtd-share_metadata_schema[OpenMinTeD publication schema]. Ultimate goal is to create an  interoperable layer for machine access to OA content from publishers for TDM purposes.

This is an dynamic page, should be updated every time a machine interface of a publisher is altered.

== Key publishers

We investigate, analyse and document the functionality exposed by APIs of publishers with respect to being able to aggregate open access content from them. We aim at implementing custom solutions for aggregating content from the following key publishers:

=== https://github.com/openminted/omtd-publisher-connector-harvester/blob/master/interoperability-layer/interoperability-layer/[Elsevier]

=== https://github.com/openminted/omtd-publisher-connector-harvester/blob/master/interoperability-layer/interoperability-layer/springer.adoc[Springer]

=== https://github.com/openminted/omtd-publisher-connector-harvester/blob/master/interoperability-layer/interoperability-layer/Wiley.adoc[Wiley]

=== https://github.com/openminted/omtd-publisher-connector-harvester/blob/master/interoperability-layer/interoperability-layer/TaylorFrancis.adoc[TaylorFrancis]

=== https://github.com/openminted/omtd-publisher-connector-harvester/blob/master/interoperability-layer/interoperability-layer/PLoS.adoc[PLoS]

== Other publishers

The content from many publishers not covered in the section above can still be collected using an approach in which we make use of the CrossRef service. 

=== https://github.com/openminted/omtd-publisher-connector-harvester/blob/master/interoperability-layer/interoperability-layer/CrossRef.adoc[CrossRef]

