== Wiley

=== Publisher APIs

Access is maintained by Crossref's https://apps.crossref.org/clickthrough/researchers/[Click-through service]. The Click-through service grants access to publisher and Crossref API's and authentication is provided by https://orcid.org/[ORCID]. To access Wiley API's, one must read and agree to the Wiley TDM license by clicking 'accept' on the Click-through service. Once accepted, keys generated by the account has access to Wiley API's.

Note: as of 2017-03-20, Wiley TDM Licenses are not availble to accept so we cannot access the API. After contacting Crossref support, they said:
____
"Wiley are in the process of updating their license and I would expect a new one to be uploaded within the week, if not sooner."
____

=== Harvesting approach

=== Limitations

[cols="3*"]
|====
|Task|Limitation|Solution

|Doi discovery
|a
|aa

|Incremental update
|b
|bb

|Imposed limits
|c
|cc

|Response formats
|d
|dd

|====

=== Proposed improvements

=== OMTD Schema Mapping
