== Wiley

=== Publisher API
Access to the API is maintained by Crossref's https://apps.crossref.org/clickthrough/researchers[Click-through] service. The click-through service manages access to both the publisher's and CrossRef's APIs. Authentication to the Click-through service is provided by https://orcid.org/[ORCID]. To access Wiley’s API, one must read and agree to the http://olabout.wiley.com/WileyCDA/Section/id-826542.html[Wiley TDM] license by clicking 'accept' on the Click-through service. Once accepted, API keys linked to the account can be used to download Wiley content according to the license terms and conditions. Once a Crossref TDM license is accepted, it is irrevocable. 


=== Information provided by the publisher
Wiley has a few pages on its website which point the user to their http://olabout.wiley.com/WileyCDA/Section/id-826542.html[TDM Policy], the agreement and how to get started with the API using Crossref. Wiley delegates API access to Crossref and leaves the user to investigate how the Crossref API works using its documentation. 

=== Aggregation approach
To use existing knowledge of the Crossref API to retrieve publication metadata and full texts - see section on Crossref.

=== Features table
See https://github.com/openminted/omtd-publisher-connector-harvester/blob/master/interoperability-layer/crossref.adoc[Crossref].

=== Limitations 

=== Recommendations
See https://github.com/openminted/omtd-publisher-connector-harvester/blob/master/interoperability-layer/crossref.adoc[Crossref].





